######################################################################
# Automatically generated by qmake (3.0) Tue Sep 3 19:15:45 2013
######################################################################

TEMPLATE = app
CONFIG += qt
QT += webkit network
HEADERS += main.h
SOURCES += main.cc
LIBS += -lglut -lGL
